#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_cr_nojoin_no_golay_parallel
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

source activate qiime1

make_2d_plots.py -i ~/2018_02_smb/SILVAcdout/bdiv_even627/unweighted_unifrac_pc.txt -m ~/2018_02_smb/map.tsv -o SILVA2d_plotsun

source deactivate
