#!/bin/bash --login
#PBS-l walltime=01:00:00
#PBS -l select=1:ncpus=1
#PBS -N 2017_cr_nojoin_no_golay_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

#load modules and qiime
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

source activate qiime1

core_diversity_analyses.py --recover_from_failure -i ~/2018_02_smb/SILVA_otus/otu_table.biom -m ~/2018_02_smb/map.tsv -t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre -o SILVAcdout -e 627

source deactivate
