#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=1
#PBS -N 2017_cr_nojoin_no_golay_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

#load modules and qiime
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

source activate qiime1

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

count_seqs.py -i ~/2018_02_smb/dem2/seqs.fna -o countseqs

source deactivate
