#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_cr_nojoin_no_golay_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

#Load Modules and qiime
module load miniconda/python2

#loading virtual environment
echo "activating virtual environment"

#setting temporary directory 
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

source activate qiime1

group_significance.py -i ~/2018_02_smb/tax_mapping/otu_table_L2.biom -m ~/2018_02_smb/map.tsv -c SamplePhosphorus -s kruskal_wallis -o kw_ocs.txt

source deactivate
